### ISSUE TITLE
Support configuration of selective application logging

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-server-core-library#8]
Currently, application logging is configured in the cedar-main.yml file as follows:

```
cache:
  persistent:
    connection:
      host: "${CEDAR_REDIS_PERSISTENT_HOST}"
      port: "${CEDAR_REDIS_PERSISTENT_PORT}"
      timeout: 2000
    queueNames:
      searchPermission: "CEDAR-QUEUE-search-permission"
      ncbiSubmission: "CEDAR-QUEUE-ncbi-submission"
      appLog: "CEDAR-QUEUE-app-log"
      valuerecommender: "CEDAR-QUEUE-valuerecommender"
```

There are four types of requests logged on the appLog queue: requestFilter, requestHandler, responseException, cypherQuery.

We would like to be able to selectively enable/disable these four types of app logging in the config file. Current suggestion is:

```
cache:
  persistent:
    connection:
      host: "${CEDAR_REDIS_PERSISTENT_HOST}"
      port: "${CEDAR_REDIS_PERSISTENT_PORT}"
      timeout: 2000
    queues:
      searchPermission: 
          queueName: "CEDAR-QUEUE-search-permission"
      ncbiSubmission: 
         queueName: "CEDAR-QUEUE-ncbi-submission"
      appLog: 
        queueName: "CEDAR-QUEUE-app-log"
        disabledAppLogTypes: 
           - "cypherQuery"
      valuerecommender: 
           queueName: "CEDAR-QUEUE-valuerecommender"
```

The above would disable Cypher query logging on the application log queue.
